### ISSUE TITLE
Is "Dissertation" in the 1st page should be lowercase?

### ISSUE THREAD

**Issue by shuaiwang88** [josephcslater/WSUThesisTemplate#2]
"A Dissertation submitted" -->"Dissertation" lowercase? 
I changed it to lowercase but in the 2nd page "dissertation director " is shown lowercase, which should be uppercase.

**Comment by josephcslater** [comment]
Please check. I just pushed a fix. 

Report back so I can close this. Thanks- JS

**Comment by shuaiwang88** [comment]
perfect!
